### ISSUE TITLE
Plugin API specs

### ISSUE THREAD

**Issue by mod** [rubykube/barong#201]
# Config

in config/plugins.yml
we list plugins
```
plugins:
 - name: bunnyware
    url: git@github.com:rubykube/bunnyware.git
    version: 1.2.0
```

Ideally we could leverage a Gemfile or bundle yaml file format (Gemfile.lock)

# Task

`rake plugin:install`

would iterate though the file if exist and install using
bundler add

this rake task is meant to be run in docker build stage.

# Initialize

Scan throught the file and require the plugins
eventually we can call a plugin.version method
and run @plugins[PluginName.name] = PluginName.new(config)
